- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop webaap
     ignore_errors: yes
   - name: remove container
     shell: docker container rm webaap
     ignore_errors: yes
   - name: remove docker image
     shell: docker image rmi bmoudgill31/devops_demo
     ignore_errors: yes
   - name: create new container
     shell: docker container run -itd --name webaap -p 8090:80 bmoudgill31/devops_demo
